{
 "title": "FB Demo Example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RapidFile Toolkit - Number of files per FS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_FB_file_count" }
   ]
  },
  {
   "title": "Top 5 Snapshot Usage FS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,flashblade_fs_snapshot_usage_bytes)"
    }
   ]
  },
  {
   "title": "RapidFile Toolkit pdu output",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_directory_size_bytes" }
   ]
  },
  {
   "title": "Healthy Blades",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Healthy Blades" }
   ],
   "targets": [
    {
     "expr": "flashblade_blade_num_healthy_blades"
    }
   ]
  },
  {
   "title": "Failed Blades",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "flashblade_blade_num_unhealthy_blades"
    }
   ]
  },
  {
   "title": "Top 10 Buckets by Object count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,flashblade_s3_object_count)\r"
    }
   ]
  }
 ]
}