#!/bin/sh

INST_DIR=`pwd`

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
printf "${GREEN}-----------------  Beginning install ------------------------${NC}\n"

printf "${GREEN}Updating system rpms....${NC}\n"
yum update -y -q

echo
printf "${GREEN}Installing wget${NC}\n"
yum -y -q install wget

echo
printf "${GREEN}Creating users: prometheus, node_exporter, pure_exporter${NC}\n"

useradd --no-create-home --shell /usr/sbin/nologin prometheus
useradd --no-create-home --shell /bin/false node_exporter
useradd --no-create-home --shell /usr/sbin/nologin pure_exporter

printf "${GREEN}Creating diretories...${NC}\n"
mkdir /etc/prometheus
mkdir /var/lib/prometheus
mkdir /tmp/prometheus

printf "${GREEN}Downloading prometheus tarball....${NC}\n"
cd /tmp/prometheus
curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest \
| grep browser_download_url  \
| grep linux-amd64 \
| cut -d '"' -f 4 \
| wget -qi -

echo
printf "${GREEN}Untarring Prometheus...${NC}\n"
cd /tmp/prometheus
tar xzf `ls *gz`


printf "${GREEN}Moving prometheus to /var/lib...${NC}\n"
cd /tmp/prometheus/`ls /tmp/prometheus|grep -v gz`

mv * /var/lib/prometheus
mv /var/lib/prometheus/prometheus.yml /etc/prometheus
ln -s /var/lib/prometheus/prometheus /usr/local/bin/prometheus

chown -R prometheus:prometheus /etc/prometheus
chown -R prometheus:prometheus /var/lib/prometheus

printf "${GREEN}Downloading node_exporter......${NC}\n"
cd /tmp/prometheus
mkdir node_exporter
cd node_exporter
wget -q https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz 
tar xzf `ls *gz`

mv node_exporter-0.18.1.linux-amd64/node_exporter /var/lib/prometheus
chown prometheus:prometheus /var/lib/prometheus/node_exporter


echo "[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online-target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus \
--web.console.templates=/var/lib/prometheus/consoles \
--collector.text.file /var/lib/prometheus/logcollect \
--web.console.libraries=/var/lib/prometheus/console_libraries 

[Install]
WantedBy=multi-user.target

" >/etc/systemd/system/prometheus.service

printf "${GREEN}Starting up Prometheus......${NC}\n"
systemctl daemon-reload
systemctl enable --now prometheus
systemctl start prometheus
sleep 5
systemctl status prometheus.service | grep "Active:"


echo "[Unit]
Description=Node Exporter

[Service]
User=prometheus
ExecStart=/var/lib/prometheus/node_exporter 

[Install]
WantedBy=default.target

" >/etc/systemd/system/node_exporter.service

printf "${GREEN}Starting up node_exporter...${NC}\n"
systemctl daemon-reload
systemctl enable --now node_exporter
systemctl start node_exporter
sleep 5
systemctl status node_exporter.service | grep "Active:"


echo "
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']
" >> /etc/prometheus/prometheus.yml 

systemctl restart prometheus
sleep 5
systemctl status prometheus | grep "Active:"

echo
printf "${GREEN}Installing grafana.......${NC}\n"
echo "[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >/etc/yum.repos.d/grafana.repo
yum -y -q install grafana

/bin/systemctl daemon-reload
/bin/systemctl enable grafana-server.service
/bin/systemctl start grafana-server.service

cd $INST_DIR
wget -q https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.13.8.linux-amd64.tar.gz

printf "${GREEN}================================================================================${NC}\n"
printf "${GREEN}Installing zip and unzip .....${NC}\n"
yum -y -q install zip
yum -y -q install unzip
echo
printf "${GREEN}================================================================================${NC}\n"
printf "${GREEN}Downloading prometheus-flashblade-exporter .....${NC}\n"
wget -q https://github.com/man-group/prometheus-flashblade-exporter/archive/master.zip
printf "${GREEN}Unzipping prometheus-flashblade-exporter .....${NC}\n"
unzip master.zip
cd prometheus-flashblade-exporter-master
PATH=$PATH:/usr/local/go/bin
export PATH
printf "${GREEN}Compiling prometheus-flashblade-exporter .....${NC}\n"
make
cp prometheus-flashblade-exporter /usr/local/bin
cd ..
rm master.zip
rm go1.13.8.linux-amd64.tar.gz
rm -r prometheus-flashblade-exporter-master
chown prometheus:prometheus /usr/local/bin/prometheus-flashblade-exporter
chmod 755 /usr/local/bin/prometheus-flashblade-exporter
printf "${GREEN}Downloading prometheus-flashblade-exporter startup file.....${NC}\n"

wget -q https://raw.githubusercontent.com/purekevin/se-dashboarding/master/start-fb-exporter
chmod 755 start-fb-exporter
./start-fb-exporter

echo "
  - job_name: 'fb_exporter'
    static_configs:
    - targets: ['localhost:9130']
" >> /etc/prometheus/prometheus.yml 
printf "${GREEN}Restarting Prometheus after updating the /etc/prometheus/prometheus.yml file...${NC}\n"
systemctl restart prometheus
sleep 5
systemctl status prometheus | grep "Active"
printf "${GREEN}-----------------  Beginning install of rapidfile toolkit ------------------------${NC}\n"
wget -q http://www.lehuaparker.com/rapidfile-1.0.0-beta.4.tar.gz
tar xzf rapidfile-1.0.0-beta.4.tar.gz
rm rapidfile-1.0.0-beta.4.tar.gz
rpm -U rapidfile-1.0.0-beta.4/rapidfile-1.0.0-beta.4-Linux.rpm

printf "${GREEN}-----------------  Beginning install nfs utils ------------------------${NC}\n"
yum -y -q install nfs-utils

mkdir /mnt1 /mnt2
echo "10.21.225.38:/da-dashboard-1   /mnt1     nfs    rw,sync,hard,intr 0 0" >>/etc/fstab
echo "10.21.225.38:/da-dashboard-2   /mnt2     nfs    rw,sync,hard,intr 0 0" >>/etc/fstab
mount /mnt1
mount /mnt2
