#!/bin/sh

INST_DIR=`pwd`

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
printf "${GREEN}-----------------  Beginning install ------------------------${NC}\n"


echo "Updating system rpms...."
yum update -y -q

echo
printf "${GREEN}Creating users: prometheus, node_exporter, pure_exporter${NC}\n"

useradd --no-create-home --shell /usr/sbin/nologin prometheus
useradd --no-create-home --shell /bin/false node_exporter
useradd --no-create-home --shell /usr/sbin/nologin pure_exporter

echo "creating diretories..."
mkdir /etc/prometheus
mkdir /var/lib/prometheus
mkdir /tmp/prometheus

echo "Downloading prometheus tarball...."
cd /tmp/prometheus
curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest \
| grep browser_download_url  \
| grep linux-amd64 \
| cut -d '"' -f 4 \
| wget -qi -

echo
echo "Untarring Prometheus..."
cd /tmp/prometheus
tar xzf `ls *gz`


echo "Moving prometheus to /var/lib..."
cd /tmp/prometheus/`ls /tmp/prometheus|grep -v gz`

mv * /var/lib/prometheus
mv /var/lib/prometheus/prometheus.yml /etc/prometheus
ln -s /var/lib/prometheus/prometheus /usr/local/bin/prometheus

chown -R prometheus:prometheus /etc/prometheus
chown -R prometheus:prometheus /var/lib/prometheus

echo "Downloading node_exporter......"
cd /tmp/prometheus
mkdir node_exporter
cd node_exporter
wget -q https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz 
tar xzf `ls *gz`

mv node_exporter-0.18.1.linux-amd64/node_exporter /var/lib/prometheus
chown prometheus:prometheus /var/lib/prometheus/node_exporter


echo "[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online-target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus \
--web.console.templates=/var/lib/prometheus/consoles \
--web.console.libraries=/var/lib/prometheus/console_libraries 

[Install]
WantedBy=multi-user.target

" >/etc/systemd/system/prometheus.service

echo "Starting up Prometheus......"
systemctl daemon-reload
systemctl enable --now prometheus
systemctl start prometheus
sleep 5
systemctl status prometheus.service | grep "Active:"



# echo "Opening up the firewall for port 9090...."
# firewall-cmd --permanent --add-port=9090/tcp
# firewall-cmd --reload


echo "[Unit]
Description=Node Exporter

[Service]
User=prometheus
ExecStart=/var/lib/prometheus/node_exporter 

[Install]
WantedBy=default.target

" >/etc/systemd/system/node_exporter.service

echo "Starting up node_exporter..."
systemctl daemon-reload
systemctl enable --now node_exporter
systemctl start node_exporter
sleep 5
systemctl status node_exporter.service | grep "Active:"


echo "
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']
" >> /etc/prometheus/prometheus.yml 

systemctl restart prometheus
sleep 5
systemctl status prometheus | grep "Active:"

echo
echo
echo
echo "================================================================================"
echo "=    Installing grafana......."
echo "--------------------------------------------------------------------------------"
echo "[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >/etc/yum.repos.d/grafana.repo
yum -y -q install grafana

/bin/systemctl daemon-reload
/bin/systemctl enable grafana-server.service
/bin/systemctl start grafana-server.service


#wget https://raw.githubusercontent.com/purekevin/se-dashboarding/master/prometheus-flashblade-exporter
#cp /home/pureuser/prometheus-flashblade-exporter /var/lib/prometheus
#ln -s /var/lib/prometheus/prometheus-flashblade-exporter /usr/local/bin/prometheus-flashblade-exporter
#chown prometheus:prometheus /var/lib/prometheus/prometheus-flashblade-exporter

cd $INST_DIR
wget -q https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.13.8.linux-amd64.tar.gz

echo "================================================================================"
echo "Installing zip ....."
yum -y -q install zip
echo
echo "================================================================================"
echo "Downloading prometheus-flashblade-exporter ....."
wget -q https://github.com/man-group/prometheus-flashblade-exporter/archive/master.zip
echo "Unzipping prometheus-flashblade-exporter ....."
unzip master.zip
cd prometheus-flashblade-exporter-master
PATH=$PATH:/usr/local/go/bin
export PATH
echo "Compiling prometheus-flashblade-exporter ....."
make
cp prometheus-flashblade-exporter /usr/local/bin
cd ..
rm master.zip
rm go1.13.8.linux-amd64.tar.gz
rm -r prometheus-flashblade-exporter-master
chown prometheus:prometheus /usr/local/bin/prometheus-flashblade-exporter
chmod 755 /usr/local/bin/prometheus-flashblade-exporter
echo "Downloading prometheus-flashblade-exporter startup file....."

wget -q https://raw.githubusercontent.com/purekevin/se-dashboarding/master/start-fb-exporter
chmod 755 start-fb-exporter
./start-fb-exporter

echo "
  - job_name: 'fb_exporter'
    static_configs:
    - targets: ['localhost:9130']
" >> /etc/prometheus/prometheus.yml 
echo "Restarting Prometheus after updating the /etc/prometheus/prometheus.yml file..."
systemctl restart prometheus
sleep 5
systemctl status prometheus | grep "Active:"

