#!/bin/sh
echo "Updating system rpms...."
yum update -y

echo -e "\n\n\n"

echo "Disabling selinux..."
sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config
setenforce 0
sestatus
echo -e  "\n\n\n"

echo "Creating users: prometheus, node_exporter, pure_exporter"
useradd --no-create-home --shell /usr/sbin/nologin prometheus
useradd --no-create-home --shell /bin/false node_exporter
useradd --no-create-home --shell /usr/sbin/nologin pure_exporter

echo "creating diretories..."
mkdir /etc/prometheus
mkdir /var/lib/prometheus
mkdir /tmp/prometheus

echo "Downloading prometheus tarball...."
cd /tmp/prometheus
curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest \
| grep browser_download_url  \
| grep linux-amd64 \
| cut -d '"' -f 4 \
| wget -qi -

echo -e "\n\n"
echo "Untarring Prometheus..."
cd /tmp/prometheus
tar xzf `ls *gz`


echo "Moving prometheus to /var/lib..."
cd /tmp/prometheus/`ls /tmp/prometheus|grep -v gz`

mv * /var/lib/prometheus
mv /var/lib/prometheus/prometheus.yml /etc/prometheus
ln -s /var/lib/prometheus/prometheus /usr/local/bin/prometheus

chown -R prometheus:prometheus /etc/prometheus
chown -R prometheus:prometheus /var/lib/prometheus

echo "Downloading node_exporter......"
cd /tmp/prometheus
mkdir node_exporter
cd node_exporter
wget -q https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz 
tar xzf `ls *gz`

mv node_exporter-0.18.1.linux-amd64/node_exporter /var/lib/prometheus
chown prometheus:prometheus /var/lib/prometheus/node_exporter


echo "[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online-target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus \
--web.console.templates=/var/lib/prometheus/consoles \
--web.console.libraries=/var/lib/prometheus/console_libraries 

[Install]
WantedBy=multi-user.target

" >/etc/systemd/system/prometheus.service

systemctl daemon-reload
systemctl enable --now prometheus
systemctl start prometheus
sleep 10
systemctl status prometheus.service



# echo "Opening up the firewall for port 9090...."
# firewall-cmd --permanent --add-port=9090/tcp
# firewall-cmd --reload


echo "[Unit]
Description=Node Exporter

[Service]
User=prometheus
ExecStart=/var/lib/prometheus/node_exporter 

[Install]
WantedBy=default.target

" >/etc/systemd/system/node_exporter.service

echo "Starting up node_exporter..."
systemctl daemon-reload
systemctl enable --now node_exporter
systemctl start node_exporter
sleep 10
systemctl status node_exporter.service


echo "
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']
" >> /etc/prometheus/prometheus.yml 

systemctl restart prometheus
sleep 10
systemctl status prometheus

echo
echo
echo
echo "================================================================================"
echo "=    Installing grafana......."
echo "--------------------------------------------------------------------------------"
echo "[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >/etc/yum.repos.d/grafana.repo
yum -y install grafana

/bin/systemctl daemon-reload
/bin/systemctl enable grafana-server.service
/bin/systemctl start grafana-server.service

yum install -y unzip

cp /home/pureuser/prometheus-flashblade-exporter /var/lib/prometheus
ln -s /var/lib/prometheus/prometheus-flashblade-exporter /usr/local/bin/prometheus-flashblade-exporter
chown prometheus:prometheus /var/lib/prometheus/prometheus-flashblade-exporter
