#!/bin/sh


echo -e "\n\n\n"

echo "Deleting users: prometheus, node_exporter, pure_exporter"
userdel -rf prometheus 2>/dev/null
userdel -rf node_exporter 2>/dev/null
userdel -rf pure_exporter 2>/dev/null

echo "creating diretories..."
rm -rf /etc/prometheus 
rm -rf /var/lib/prometheus 
rm -rf /tmp/prometheus 



#echo "Re-enabling selinux..."

#sed -i s/^SELINUX=.*$/SELINUX=enforcing/ /etc/selinux/config
#setenforce 1
#sestatus

rm -rf /usr/local/bin/prometheus 
rm -rf /usr/lib/systemd/system/prometheus.service 


systemctl disable --now node_exporter 
systemctl stop node_exporter 
systemctl status node_exporter 

systemctl status prometheus 
systemctl disable --now prometheus 
systemctl stop prometheus 
systemctl status prometheus 

rm -rf /etc/systemd/system/prometheus.service /etc/systemd/system/node_exporter.service 

/bin/systemctl stop grafana-server.service
/bin/systemctl disable grafana-server.service 
/bin/systemctl daemon-reload 

yum erase -y grafana 
rm -rf /etc/yum.repos.d/grafana.repo 



rm -rf /etc/grafana 
rm -rf /usr/share/grafana 
rm -rf /var/log/grafana 
rm -rf /var/lib/yum/repos/x86_64/7/grafana 
rm -rf /var/lib/grafana 
rm -rf /var/cache/yum/x86_64/7/grafana 

rm -rf /usr/local/bin/prometheus-flashblade-exporter 
